# Generated by Django 6.1.1 on 2026-09-20 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_automationaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergySaving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power_saved_watts', models.FloatField(default=0)),
                ('duration_hours', models.FloatField(default=0)),
                ('energy_saved_kwh', models.FloatField(default=0)),
                ('estimated_cost_saved', models.FloatField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('automation_action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='energy_savings', to='devices.automationaction')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='energy_savings', to='devices.device')),
            ],
        ),
    ]
