# Generated by Django 6.1.1 on 2026-09-20 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_energysaving'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(max_length=50),
        ),
    ]
