# Generated by Django 6.1.1 on 2026-09-20 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_alter_device_device_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='energysaving',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
